version: "3.8"
services:
  mysqldb:
    image: mariadb:latest # Cambié a MariaDB, que es más compatible con ARM
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=coinscontrol
    ports:
      - 3307:3306
    networks:
      - mysql-phpmyadmin
    volumes:
      - db_data:/var/lib/mysql
    # No es necesario especificar platform aquí, MariaDB debería funcionar en ARM
  app:
    build: .
    depends_on:
      - mysqldb
    ports:
      - 3005:3005
    networks:
      - mysql-phpmyadmin
  phpmyadmin:
    depends_on:
      - mysqldb
    image: phpmyadmin:latest # Asegúrate de que esta versión sea compatible
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_HOST=mysqldb
      - MARIADB_ROOT_PASSWORD=root
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data:
