services:
  mysqldb:
    image: mysql:5.7 # Imagen oficial de MySQL
    platform: linux/arm/v8 # Especificar la plataforma ARM
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=coinscontrol
    ports:
      - 3307:3306
    networks:
      - mysql-phpmyadmin
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    depends_on:
      - mysqldb
    ports:
      - 3005:3005
    networks:
      - mysql-phpmyadmin
  phpmyadmin:
    depends_on:
      - mysqldb
    image: phpmyadmin:latest # Asegúrate de que esta imagen sea compatible
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_HOST=mysqldb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data:
