services:
  mysqldb:
    image: mysql # Imagen oficial de MySQL
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=coinscontrol
    ports:
      - 3308:3306
    networks:
      - mysql-phpmyadmin
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    depends_on:
      - mysqldb
    ports:
      - 3006:3006
    networks:
      - mysql-phpmyadmin
  phpmyadmin:
    depends_on:
      - mysqldb
    image: phpmyadmin # Asegúrate de que esta imagen sea compatible
    restart: always
    ports:
      - 80:80
    environment:
      - PMA_HOST=mysqldb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:
    driver: bridge
volumes:
  db_data:
