version: "3.8"
services:
  mysqldb:
    image: mysql # Usa una versión compatible
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=coinscontrol
    ports:
      - 3307:3306
    networks:
      - mysql-phpmyadmin
    volumes:
      - db_data:/var/lib/mysql
    platform: linux/arm64
  app:
    build: .
    depends_on:
      - mysqldb
    ports:
      - 3005:3005
    networks:
      - mysql-phpmyadmin
  phpmyadmin:
    depends_on:
      - mysqldb
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8090:80
    environment:
      - PMA_HOST=mysqldb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data:
